package tablegen;

public class ID3FrameTypes {

	private static final String[][] TYPES = {
		{"ALBUM_TITLE", "TALB"},
		{"ALBUM_SORT_ORDER", "TSOA"},
		{"ARTIST", "TPE1"},
		{"ATTACHED_PICTURE", "APIC"},
		{"AUDIO_ENCRYPTION", "AENC"},
		{"AUDIO_SEEK_POINT_INDEX", "ASPI"},
		{"BAND", "TPE2"},
		{"BEATS_PER_MINUTE", "TBPM"},
		{"COMMENTS", "COMM"},
		{"COMMERCIAL_FRAME", "COMR"},
		{"COMMERCIAL_INFORMATION", "WCOM"},
		{"COMPOSER", "TCOM"},
		{"CONDUCTOR", "TPE3"},
		{"CONTENT_GROUP_DESCRIPTION", "TIT1"},
		{"CONTENT_TYPE", "TCON"},
		{"COPYRIGHT", "WCOP"},
		{"COPYRIGHT_MESSAGE", "TCOP"},
		{"ENCODED_BY", "TENC"},
		{"ENCODING_TIME", "TDEN"},
		{"ENCRYPTION_METHOD_REGISTRATION", "ENCR"},
		{"EQUALISATION", "EQU2"},
		{"EVENT_TIMING_CODES", "ETCO"},
		{"FILE_OWNER", "TOWN"},
		{"FILE_TYPE", "TFLT"},
		{"GENERAL_ENCAPSULATED_OBJECT", "GEOB"},
		{"GROUP_IDENTIFICATION_REGISTRATION", "GRID"},
		{"INITIAL_KEY", "TKEY"},
		{"INTERNET_RADIO_STATION_NAME", "TRSN"},
		{"INTERNET_RADIO_STATION_OWNER", "TRSO"},
		{"MODIFIED_BY", "TPE4"},
		{"INVOLVED_PEOPLE_LIST", "TIPL"},
		{"INTERNATIONAL_STANDARD_RECORDING_CODE", "TSRC"},
		{"LANGUAGES", "TLAN"},
		{"LENGTH", "TLEN"},
		{"LINKED_INFORMATION", "LINK"},
		{"LYRICIST", "TEXT"},
		{"MEDIA_TYPE", "TMED"},
		{"MOOD", "TMOO"},
		{"MPEG_LOCATION_LOOKUP_TABLE", "MLLT"},
		{"MUSICIAN_CREDITS_LIST", "TMCL"},
		{"MUSIC_CD_IDENTIFIER", "MCDI"},
		{"OFFICIAL_ARTIST_WEBPAGE", "WOAR"},
		{"OFFICIAL_AUDIO_FILE_WEBPAGE", "WOAF"},
		{"OFFICIAL_AUDIO_SOURCE_WEBPAGE", "WOAS"},
		{"OFFICIAL_INTERNET_RADIO_STATION_HOMEPAGE", "WORS"},
		{"ORIGINAL_ALBUM_TITLE", "TOAL"},
		{"ORIGINAL_ARTIST", "TOPE"},
		{"ORIGINAL_FILENAME", "TOFN"},
		{"ORIGINAL_LYRICIST", "TOLY"},
		{"ORIGINAL_RELEASE_TIME", "TDOR"},
		{"OWNERSHIP_FRAME", "OWNE"},
		{"PART_OF_A_SET", "TPOS"},
		{"PAYMENT", "WPAY"},
		{"PERFORMER_SORT_ORDER", "TSOP"},
		{"PLAYLIST_DELAY", "TDLY"},
		{"PLAY_COUNTER", "PCNT"},
		{"POPULARIMETER", "POPM"},
		{"POSITION_SYNCHRONISATION_FRAME", "POSS"},
		{"PRIVATE_FRAME", "PRIV"},
		{"PRODUCED_NOTICE", "TPRO"},
		{"PUBLISHER", "TPUB"},
		{"PUBLISHERS_OFFICIAL_WEBPAGE", "WPUB"},
		{"RECOMMENDED_BUFFER_SIZE", "RBUF"},
		{"RECORDING_TIME", "TDRC"},
		{"RELATIVE_VOLUME_ADJUSTMENT", "RVA2"},
		{"RELEASE_TIME", "TDRL"},
		{"REVERB", "RVRB"},
		{"SEEK_FRAME", "SEEK"},
		{"SET_SUBTITLE", "TSST"},
		{"SIGNATURE_FRAME", "SIGN"},
		{"ENCODING_TOOLS_AND_SETTINGS", "TSSE"},
		{"SUBTITLE", "TIT3"},
		{"SYNCHRONISED_LYRIC", "SYLT"},
		{"SYNCHRONISED_TEMPO_CODES", "SYTC"},
		{"TAGGING_TIME", "TDTG"},
		{"TERMS_OF_USE", "USER"},
		{"TITLE", "TIT2"},
		{"TITLE_SORT_ORDER", "TSOT"},
		{"TRACK_NUMBER", "TRCK"},
		{"UNIQUE_FILE_IDENTIFIER", "UFID"},
		{"UNSYNCHRONISED_LYRIC", "USLT"},
		{"USER_DEFINED_TEXT_INFORMATION_FRAME", "TXXX"},
		{"USER_DEFINED_URL_LINK_FRAME", "WXXX"}
	};

	public static void main(String[] args) {
		for(int i = 0; i<TYPES.length; i++) {
			System.out.println("static final int "+TYPES[i][0]+" = "+toInt(TYPES[i][1])+"; //"+TYPES[i][1]);
		}
	}

	private static int toInt(String s) {
		int x = 0;
		for(int i = 0; i<4; i++) {
			x <<= 8;
			x |= s.charAt(i);
		}
		return x;
	}
}
